
@set _GITHUB_METHOD=%1
@set _GITHTUB_REPO=%2
@set _GITHUB_USER_NAME=XXXXXX
@set _GITHUB_PASSWORD=XXXXXX
@set _GITHUB_TOOL_HOME=XXXXXX

@call jdk16
@call java -jar %_GITHUB_TOOL_HOME%\codjo-tools-github.jar %_GITHUB_METHOD% %_GITHUB_USER_NAME% %_GITHUB_PASSWORD% %_GITHTUB_REPO%